# Day 1 — Supervised Learning Concepts & the Scikit-learn API

    In this notebook the data used is the American Housing Dataset.
    The target to be predicted is the "Price" of houses based on their corresponding features.

## Step 1 - Sperate Data Into Features & Target

In [46]:
%pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: narwhals>=2.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [47]:
import pandas as pd

Scikit-learn and pandas library installed/imported.

In [48]:
housing_data = pd.read_csv("American_Housing_Data.csv")
housing_data

,Zip Code,Price,Beds,Baths,Living Space,Address,City,State,Zip Code Population,Zip Code Density,County,Median Household Income,Latitude,Longitude
0,10013,3999000.0,2,3,1967,74 GRAND ST APT 3,New York,New York,29563,20967.9,New York,370046.0,40.72001,-74.00472
1,10013,3999000.0,2,3,1967,74 GRAND ST APT 3,New York,New York,29563,20967.9,New York,370046.0,40.72001,-74.00472
2,10014,1650000.0,1,1,718,140 CHARLES ST APT 4D,New York,New York,29815,23740.9,New York,249880.0,40.73407,-74.00601
3,10014,760000.0,3,2,1538,38 JONES ST,New York,New York,29815,23740.9,New York,249880.0,40.73407,-74.00601
4,10014,1100000.0,1,1,600,81 BEDFORD ST APT 3F,New York,New York,29815,23740.9,New York,249880.0,40.73407,-74.00601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39976,98199,2495000.0,4,4,3380,2626 27TH AVE W,Seattle,Washington,22890,2086.8,King,205611.0,47.65139,-122.40223
39977,98199,2295000.0,4,4,2878,3215 32ND AVE W,Seattle,Washington,22890,2086.8,King,205611.0,47.65139,-122.40223
39978,98199,950000.0,3,2,1380,3257 22ND AVE W,Seattle,Washington,22890,2086.8,King,205611.0,47.65139,-122.40223
39979,98199,425000.0,2,1,856,3711 26TH PL W APT 102,Seattle,Washington,22890,2086.8,King,205611.0,47.65139,-122.40223
39980,98199,1150000.0,3,3,2840,2911 25TH AVE W,Seattle,Washington,22890,2086.8,King,205611.0,47.65139,-122.40223

In [49]:
x = housing_data.drop("Price", axis = 1)
y = housing_data["Price"]

The "price" column was seperated from the dataframe and labeled as "y"

## Step 2 - Train/Test Split

In [50]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [60]:
print("X_train")
X_train

X_train

,Zip Code,Beds,Baths,Living Space,Address,City,State,Zip Code Population,Zip Code Density,County,Median Household Income,Latitude,Longitude
26889,80249,2,1,829,18831 E 58TH AVE UNIT A,Denver,Colorado,36640,296.8,Denver,100812.0,39.84964,-104.69496
19825,74133,4,3,3089,9226 S 73RD EAST AVE,Tulsa,Oklahoma,47158,1332.3,Tulsa,101960.0,36.04113,-95.87955
31632,89121,3,2,1672,2529 BOISE ST,Las Vegas,Nevada,66455,2795.0,Clark,68433.0,36.12141,-115.09135
15297,64117,2,1,1100,4444 N CYPRESS AVE,Kansas City,Missouri,14677,938.2,Clay,66848.0,39.16522,-94.52251
6826,32220,3,1,1216,8020 MARINER ST,Jacksonville,Florida,12020,120.3,Duval,84845.0,30.33693,-81.85335
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,30339,3,2,1784,3084 VININGS FERRY DR SE,Atlanta,Georgia,33230,1299.7,Cobb,135382.0,33.86786,-84.46483
11284,43230,3,3,1251,3861 DEER KNOLL DR,Columbus,Ohio,58956,1115.6,Franklin,107912.0,40.03648,-82.87057
38158,95838,4,2,1990,5113 NALI CT,Sacramento,California,41438,1738.1,Sacramento,76618.0,38.64708,-121.44312
860,19130,5,4,3590,601 N 18TH ST,Philadelphia,Pennsylvania,29378,9166.1,Philadelphia,138891.0,39.96760,-75.17495
15795,64157,3,2,1929,10816 N SKILES AVE,Kansas City,Missouri,21539,769.5,Clay,165544.0,39.27657,-94.47103

In [61]:
print("X_test")
X_test

X_test

,Zip Code,Beds,Baths,Living Space,Address,City,State,Zip Code Population,Zip Code Density,County,Median Household Income,Latitude,Longitude
7602,33133,3,3,2180,3057 MARY ST,Miami,Florida,34434,3194.2,Miami-Dade,164713.0,25.72983,-80.24327
9287,38117,3,2,1200,345 S WHITE STATION RD,Memphis,Tennessee,26584,1093.2,Shelby,136370.0,35.11504,-89.90551
37271,95133,3,4,1988,1902 NEVETS LN,San Jose,California,28902,3421.6,Santa Clara,173587.0,37.37171,-121.86057
33058,90807,3,3,2499,3805 LINDEN AVE,Long Beach,California,32994,2881.6,Los Angeles,122666.0,33.83098,-118.18113
22916,77033,3,2,1339,6039 WILLOW GLEN DR,Houston,Texas,28669,1939.0,Harris,54026.0,29.66801,-95.33801
...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,19132,3,1,1726,2514 W CUMBERLAND ST,Philadelphia,Pennsylvania,32802,5879.3,Philadelphia,48243.0,39.99649,-75.17102
4322,27610,2,2,1502,7004 FARMDALE RD,Raleigh,North Carolina,79445,679.4,Wake,77917.0,35.74350,-78.54644
17340,68135,5,4,4132,16107 MONROE ST,Omaha,Nebraska,29860,1465.7,Douglas,159717.0,41.20520,-96.19576
20427,75216,3,1,1335,2624 MARFA AVE,Dallas,Texas,55108,1434.1,Dallas,48821.0,32.71158,-96.78256
17735,70115,2,2,1624,4520 LAUREL ST,New Orleans,Louisiana,34261,3439.2,Orleans,141812.0,29.92375,-90.10219

In [62]:
print("y_train")
y_train

y_train

26889    300000.0
19825    424900.0
31632    415000.0
15297    159900.0
6826     127500.0
           ...
6265     505000.0
11284    320000.0
38158    534000.0
860      985000.0
15795    330000.0
Name: Price, Length: 31984, dtype: float64

In [63]:
print("y_test")
y_test

y_test

7602     1590000.0
9287      249900.0
37271    1238000.0
33058    1095000.0
22916     179000.0
           ...
890       130000.0
4322      539900.0
17340     499900.0
20427     265000.0
17735     570000.0
Name: Price, Length: 7997, dtype: float64

    The dataframe was split into 80% training rows and 20% testing rows of the overall number of rows.
    "random_state=42" was used to insure that the same data will be produced and used every time the code runs.

## Step 3 - Shapes of Tesing Training Sets

In [55]:
print("Training features rows:",X_train.shape[0] )
print("Training target rows:", y_train.shape[0] )

Training features rows: 31984
Training target rows: 31984

The training rows' numbers are identical which verifies dataframe consistencey after splitting.

In [56]:
print("Testing features rows:", X_test.shape[0])
print("Testing target rows:", y_test.shape[0])

Testing features rows: 7997
Testing target rows: 7997

Testing rows' numbers are identical which also verifies dataframe consistency after splitting.

In [57]:
print("Total features rows:",X_train.shape[0] + X_test.shape[0])
print("Total target rows:",y_train.shape[0] + y_test.shape[0])

Total features rows: 39981
Total target rows: 39981

The sum of all training and tesing rows is exactly equal to the initial dataset number of rows.

In [58]:
print("Number of Training (feature) columns:", len(X_train.columns))
print("Number of Testing (feature) columns:", len(X_test.columns))

Number of Training (feature) columns: 13
Number of Testing (feature) columns: 13

The # feature columns  = # overall dataset columns -  # extracted only one target column, which is 13 in this case.

## Step 4 - Why the model must never see the test set during training?

When the test set is used during training the model it will produce highly accurate results that are considered misleading. That is because the model records or memorises the results. Consequently, it will produce incorrect results when dealing with new datasets since no pattern recognition mechanism has been developed by the model.